preserve was replaced by merges
    ❯ git pull --rebase=preserve
    error: preserve: 'preserve' superseded by 'merges'
    error: Invalid value for --rebase: preserve

git-rebase also renamed `--preserve-merges` to `--rebase-merges`.